package com.example.clickhouse.datasource;

import java.sql.*;

/**
 * Statement wrapper that reports network errors back to the connection
 */
public class ShardAwareStatement implements Statement {
    
    private final Statement delegate;
    private final ShardAwareConnection connection;
    
    public ShardAwareStatement(Statement delegate, ShardAwareConnection connection) {
        this.delegate = delegate;
        this.connection = connection;
    }
    
    private void handleException(SQLException e) throws SQLException {
        connection.handleStatementException(e);
    }
    
    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        try {
            return delegate.executeQuery(sql);
        } catch (SQLException e) {
            handleException(e);
            return null; // Never reached
        }
    }
    
    @Override
    public int executeUpdate(String sql) throws SQLException {
        try {
            return delegate.executeUpdate(sql);
        } catch (SQLException e) {
            handleException(e);
            return 0; // Never reached
        }
    }
    
    @Override
    public boolean execute(String sql) throws SQLException {
        try {
            return delegate.execute(sql);
        } catch (SQLException e) {
            handleException(e);
            return false; // Never reached
        }
    }
    
    // Delegate all other methods
    @Override
    public void close() throws SQLException {
        delegate.close();
    }
    
    @Override
    public int getMaxFieldSize() throws SQLException {
        return delegate.getMaxFieldSize();
    }
    
    @Override
    public void setMaxFieldSize(int max) throws SQLException {
        delegate.setMaxFieldSize(max);
    }
    
    @Override
    public int getMaxRows() throws SQLException {
        return delegate.getMaxRows();
    }
    
    @Override
    public void setMaxRows(int max) throws SQLException {
        delegate.setMaxRows(max);
    }
    
    @Override
    public void setEscapeProcessing(boolean enable) throws SQLException {
        delegate.setEscapeProcessing(enable);
    }
    
    @Override
    public int getQueryTimeout() throws SQLException {
        return delegate.getQueryTimeout();
    }
    
    @Override
    public void setQueryTimeout(int seconds) throws SQLException {
        delegate.setQueryTimeout(seconds);
    }
    
    @Override
    public void cancel() throws SQLException {
        delegate.cancel();
    }
    
    @Override
    public SQLWarning getWarnings() throws SQLException {
        return delegate.getWarnings();
    }
    
    @Override
    public void clearWarnings() throws SQLException {
        delegate.clearWarnings();
    }
    
    @Override
    public void setCursorName(String name) throws SQLException {
        delegate.setCursorName(name);
    }
    
    @Override
    public ResultSet getResultSet() throws SQLException {
        return delegate.getResultSet();
    }
    
    @Override
    public int getUpdateCount() throws SQLException {
        return delegate.getUpdateCount();
    }
    
    @Override
    public boolean getMoreResults() throws SQLException {
        return delegate.getMoreResults();
    }
    
    @Override
    public void setFetchDirection(int direction) throws SQLException {
        delegate.setFetchDirection(direction);
    }
    
    @Override
    public int getFetchDirection() throws SQLException {
        return delegate.getFetchDirection();
    }
    
    @Override
    public void setFetchSize(int rows) throws SQLException {
        delegate.setFetchSize(rows);
    }
    
    @Override
    public int getFetchSize() throws SQLException {
        return delegate.getFetchSize();
    }
    
    @Override
    public int getResultSetConcurrency() throws SQLException {
        return delegate.getResultSetConcurrency();
    }
    
    @Override
    public int getResultSetType() throws SQLException {
        return delegate.getResultSetType();
    }
    
    @Override
    public void addBatch(String sql) throws SQLException {
        delegate.addBatch(sql);
    }
    
    @Override
    public void clearBatch() throws SQLException {
        delegate.clearBatch();
    }
    
    @Override
    public int[] executeBatch() throws SQLException {
        try {
            return delegate.executeBatch();
        } catch (SQLException e) {
            handleException(e);
            return null; // Never reached
        }
    }
    
    @Override
    public Connection getConnection() throws SQLException {
        return connection;
    }
    
    @Override
    public boolean getMoreResults(int current) throws SQLException {
        return delegate.getMoreResults(current);
    }
    
    @Override
    public ResultSet getGeneratedKeys() throws SQLException {
        return delegate.getGeneratedKeys();
    }
    
    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        try {
            return delegate.executeUpdate(sql, autoGeneratedKeys);
        } catch (SQLException e) {
            handleException(e);
            return 0; // Never reached
        }
    }
    
    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        try {
            return delegate.executeUpdate(sql, columnIndexes);
        } catch (SQLException e) {
            handleException(e);
            return 0; // Never reached
        }
    }
    
    @Override
    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        try {
            return delegate.executeUpdate(sql, columnNames);
        } catch (SQLException e) {
            handleException(e);
            return 0; // Never reached
        }
    }
    
    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        try {
            return delegate.execute(sql, autoGeneratedKeys);
        } catch (SQLException e) {
            handleException(e);
            return false; // Never reached
        }
    }
    
    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        try {
            return delegate.execute(sql, columnIndexes);
        } catch (SQLException e) {
            handleException(e);
            return false; // Never reached
        }
    }
    
    @Override
    public boolean execute(String sql, String[] columnNames) throws SQLException {
        try {
            return delegate.execute(sql, columnNames);
        } catch (SQLException e) {
            handleException(e);
            return false; // Never reached
        }
    }
    
    @Override
    public int getResultSetHoldability() throws SQLException {
        return delegate.getResultSetHoldability();
    }
    
    @Override
    public boolean isClosed() throws SQLException {
        return delegate.isClosed();
    }
    
    @Override
    public void setPoolable(boolean poolable) throws SQLException {
        delegate.setPoolable(poolable);
    }
    
    @Override
    public boolean isPoolable() throws SQLException {
        return delegate.isPoolable();
    }
    
    @Override
    public void closeOnCompletion() throws SQLException {
        delegate.closeOnCompletion();
    }
    
    @Override
    public boolean isCloseOnCompletion() throws SQLException {
        return delegate.isCloseOnCompletion();
    }
    
    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {
        if (iface.isAssignableFrom(getClass())) {
            return iface.cast(this);
        }
        return delegate.unwrap(iface);
    }
    
    @Override
    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        return iface.isAssignableFrom(getClass()) || delegate.isWrapperFor(iface);
    }
}